#include "RecordingMonitor.h"
#include "Logger.h"
#include <vector>
RecordingMonitor* RecordingMonitor::instance_=nullptr;
RecordingMonitor::RecordingMonitor(std::filesystem::path d,bool w,HotkeyCallback h,FileCallback f):directory_(std::move(d)),watch_(w),hotkey_(std::move(h)),file_(std::move(f)){instance_=this;if(watch_)watcher_=std::jthread([this](std::stop_token s){Watch(s);});}
RecordingMonitor::~RecordingMonitor(){Stop();instance_=nullptr;}
bool RecordingMonitor::InstallHook(){hook_=SetWindowsHookExW(WH_KEYBOARD_LL,HookProc,GetModuleHandleW(nullptr),0);return hook_!=nullptr;}
LRESULT CALLBACK RecordingMonitor::HookProc(int code,WPARAM w,LPARAM l){if(code==HC_ACTION&&instance_){auto*k=reinterpret_cast<KBDLLHOOKSTRUCT*>(l);if(k->vkCode==VK_F9){bool down=w==WM_KEYDOWN||w==WM_SYSKEYDOWN;if(down&&!instance_->f9Down_.exchange(true)&&((GetAsyncKeyState(VK_MENU)&0x8000)||(k->flags&LLKHF_ALTDOWN))){auto n=std::chrono::steady_clock::now();if(instance_->lastHotkey_.time_since_epoch().count()==0||n-instance_->lastHotkey_>std::chrono::milliseconds(400)){instance_->lastHotkey_=n;instance_->hotkey_();}}if(w==WM_KEYUP||w==WM_SYSKEYUP)instance_->f9Down_=false;}}return CallNextHookEx(instance_?instance_->hook_:nullptr,code,w,l);}
void RecordingMonitor::RunMessageLoop(std::stop_token s){MSG m{};while(!s.stop_requested()){while(PeekMessageW(&m,nullptr,0,0,PM_REMOVE)){TranslateMessage(&m);DispatchMessageW(&m);}Sleep(20);}}
void RecordingMonitor::Stop(){if(hook_){UnhookWindowsHookEx(hook_);hook_=nullptr;}if(watcher_.joinable()){watcher_.request_stop();CancelSynchronousIo(watcher_.native_handle());watcher_.join();}}
void RecordingMonitor::Watch(std::stop_token s){HANDLE h=CreateFileW(directory_.c_str(),FILE_LIST_DIRECTORY,FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE,nullptr,OPEN_EXISTING,FILE_FLAG_BACKUP_SEMANTICS,nullptr);if(h==INVALID_HANDLE_VALUE){Logger::Get().Warn("NVIDIA directory unavailable: "+directory_.string());return;}std::vector<BYTE>b(64*1024);while(!s.stop_requested()){DWORD n=0;if(!ReadDirectoryChangesW(h,b.data(),(DWORD)b.size(),TRUE,FILE_NOTIFY_CHANGE_FILE_NAME|FILE_NOTIFY_CHANGE_SIZE,&n,nullptr,nullptr)){Sleep(1000);continue;}for(auto*p=reinterpret_cast<FILE_NOTIFY_INFORMATION*>(b.data());;){std::filesystem::path q=directory_/std::wstring(p->FileName,p->FileNameLength/sizeof(wchar_t));auto e=q.extension().wstring();const bool video=_wcsicmp(e.c_str(),L".mp4")==0||_wcsicmp(e.c_str(),L".mkv")==0||_wcsicmp(e.c_str(),L".mov")==0;const bool relevant=p->Action==FILE_ACTION_ADDED||p->Action==FILE_ACTION_RENAMED_NEW_NAME||p->Action==FILE_ACTION_MODIFIED;if(video&&relevant)file_(q);if(!p->NextEntryOffset)break;p=reinterpret_cast<FILE_NOTIFY_INFORMATION*>(reinterpret_cast<BYTE*>(p)+p->NextEntryOffset);}}CloseHandle(h);}
